server:
  port: 8080

spring:
  application:
    name: userservice
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/realms/myrealm1/protocol/openid-connect/certs


  eureka:
    client:
      service-url:
        defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
