spring.datasource.url=jdbc:postgresql://localhost:5432/csek_userrequirement_db
spring.datasource.username=csek
spring.datasource.password=csek1234

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=7070

